opts_version: 2

sim_opts:
  n_epochs: 1
  # n_epochs: 2
  n_vals: 50
  val_epoch: true
  rng_seed: 1234
  # dataset: cifar10
  dataset: usps
  # dataset: mnist
  n_train: 50000
  # n_train: 10000
  n_test: 10000

block_opts:
  gpu: false
  blocks:
    - index: 1
      inputs: 0
      model: lenet
      cc: true
      positive_weights: false
      conv_strategy: patchwise
      sigma: 0.01
      init: rand32
      # middle_activation: relu
      middle_activation: sigmoid_fast
      layer_norm: true
      post_synaptic: false
      immediate: false
      bias: false
      beta_d: 0.001
      beta_rule: wta
      learning_rule: fuzzyart

    - index: 2
      inputs: 1
      model: dense
      # model: fuzzy
      cc: true
      positive_weights: false
      init: rand32
      post_synaptic: false
      # middle_activation: relu
      middle_activation: sigmoid_fast
      immediate: false
      layer_norm: true
      bias: false
      beta_d: 0.01
      n_neurons: [84,]
      learning_rule: fuzzyart
      beta_rule: wta
      beta_normalize: true

    - index: 3
      inputs: 2
      model: fuzzyartmap
      rho: 0.2
      beta_s: 0.001
      # final_sigmoid: false
      # # cc: false
      # positive_weights: false
      # init: glorot_uniform
      # post_synaptic: false
      # middle_activation: relu
      # immediate: false
      # layer_norm: true
      # bias: false
      # eta: 0.01