name: CI
# Run on master, tags, or any pull request
on:
# schedule:
#   - cron: '0 2 * * *'  # Daily at 2 AM UTC (8 PM CST)
  push:
    branches: [main]
    tags: ["*"]
  pull_request:

# Cancel ongoing tests if pushing to branch again before the previous
# build is finished.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          # - "1.6"  # LTS
          - "1"    # Latest Release
        os:
          - ubuntu-latest
        arch:
          - x64
    env:
      # Set this to download test data outside of repo
      DATADEPS_ALWAYS_ACCEPT: true
    steps:
      # Checkout the repo
      - uses: actions/checkout@v4

      # Setup Julia
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}

      # Cache Julia artifacts for faster workflow runs
      - uses: julia-actions/cache@v2

      # Build the Julia package
      - uses: julia-actions/julia-buildpkg@latest
      - run: |
          git config --global user.name Tester
          git config --global user.email te@st.er

      # Run the tests
      - uses: julia-actions/julia-runtest@latest

      # Process coverage
      - uses: julia-actions/julia-processcoverage@v1

      # Upload coverage to Codecov and Coveralls
      - name: Codecov
        uses: codecov/codecov-action@v4
        with:
          file: lcov.info

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: lcov.info
