name: Onefetcher

on:
  workflow_dispatch:
  push:
    branches:
      - onefetcher

jobs:
  build:
    runs-on: ap6yc/onefetcher:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Install onefetch
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y onefetch

      - name: Run onefetch
        run: onefetch
